### ISSUE TITLE
Events list page -- UI

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#323]
Create UI for Events List page.
**Figma link** -- https://www.figma.com/file/a7n18og4IhlfQr9bvj5pzC/Nullcast-design-share?node-id=386%3A332
Events are listed under this route.
route: /events

![image](https://user-images.githubusercontent.com/42433480/139411717-b544bf72-d553-4f44-9dac-f441819078c7.png)

**Comment by ivanetra** [comment]
Is it true that I shouldn't integrate the UI with the service, @thealpha93 ? Because it looks like the service for the event list hasn't been created yet

**Comment by thealpha93** [comment]
@ivanetra The api for it was just completed. If you wanna go at it here's the documentation

https://test-api.nullcast.dev/api/v1/doc#tag/Event/paths/~1api~1v1~1events/get

**Comment by ivanetra** [comment]
Okay. Thank you for the information!

**Comment by thealpha93** [comment]
@ivanetra If you would like to collaborate more directly with us, you can join our discord channel

https://discord.gg/UNqCpTAU

**Comment by ivanetra** [comment]
I will join soon

**Comment by thealpha93** [comment]
Thanks. Looking forward to that !
