### ISSUE TITLE
Events Details page -- UI

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#324]
Create UI for Events Details page.
**Figma link** -- https://www.figma.com/file/a7n18og4IhlfQr9bvj5pzC/Nullcast-design-share?node-id=386%3A332
Events are listed under this route.
route:  events/<event_id>

**Comment by thealpha93** [comment]
@SaharshSamir Are you still doing this issue? Or should I assign it someone else ?

**Comment by SaharshSamir** [comment]
sorry i have exams coming up so i won't be able to do it. You can assign it to someone else

**Comment by thealpha93** [comment]
@SaharshSamir It's alright. I'll assign to @codejijo
