### ISSUE TITLE
Update the env.example file

### ISSUE THREAD

**Issue by Aashiq-Otp** [Planet-NULLCAST/curriculum#327]
**Additional Context**
-  The env sample does not contain the suitable variables for **development** purpose

**Comment by thealpha93** [comment]
@Aashiq-Otp Also can you add in the documentation that the latest code is in the `development` branch?

**Comment by Aashiq-Otp** [comment]
> @Aashiq-Otp Also can you add in the documentation that the latest code is in the `development` branch?

sure
