### ISSUE TITLE
Confirmation Success Toast message missing when users got Signed up

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#340]
Success Toast message missing when users got Signed up

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/curriculum
2. Click on Login Button, where user gets redirected to Login page
3. Click on Sign Up button where the user gets redirected to the Sign Up page
4. After filling all the data in the Sign up page and when user is Signed up, the confirmation Success Toast message is missing.

**Expected behavior**
When users get Signed up, the Confirmation Success Toast message should be displayed in the Sign up page

**Recording attached**
https://www.loom.com/share/440e01741b7f47e080546ae759cc145a

**Desktop (please complete the following information):** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
**Smartphone:** not tested

**Additional context**
Tested in test site

**Comment by kunwar-11** [comment]
will try to give it a shot

**Comment by that-coder** [comment]
Assigned to you. Happy Hacking!
