### ISSUE TITLE
Redirecting Hyperlinks to be added in the Forgot Password page, for the Users to land back into the Login page

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#345]
Redirecting Hyperlinks to be added in the Forgot Password page, for the Users to land back into the Login page, once the users completes the Resetting process; of if he/she remembers the Password.

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. Click on Login Button, where user gets redirected to Login page
3. Scroll down to the "Forgot Password" Hyperlink, which when clicked by the user, gets redirected to the "Forgot Password" page
4. Redirecting Hyperlinks to be added in the Forgot Password page, for the Users to land back into the Login page, if the User remembers the Password;
5. Also Redirecting Hyperlinks to be added in the Forgot Password page, for the Users when completing the resetting password process.
 
**Expected behavior**
Redirecting Hyperlinks to be displayed in the Forgot Password page, for the Users to land back into the Login page, once the users completes the Resetting process; of if he/she remembers the Password.

**Screenshot attached**
![Forgot-Password-Nullcast](https://user-images.githubusercontent.com/92918179/139644223-6de1d631-9e7e-40c1-969a-eb8876085b1f.png)

**Desktop (please complete the following information):** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
**Smartphone:** not tested

**Additional context**
Tested in test site

**Comment by JiaHua-Zou** [comment]
I would like to tackle this problem.

**Comment by thealpha93** [comment]
Here you go @JiaHua-Zou .
Make sure you branch out from the `development` branch. It has the latest code. Thanks
