### ISSUE TITLE
"Subscribe Our Newsletter" feature to be implemented in Nullcast application

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#352]
"Subscribe Our Newsletter" feature to be implemented in Nullcast application

**To Reproduce**
1. Go to https://test-app.nullcast.dev/
2. Scroll down to the bottom of the Home page, where user could see the "Subscribe Our Newsletter" heading and an Email ID field with a "Subscribe" Button.
3. User when adds the Email ID on the field and when clicked on the "Subscribe" button have to populate the Success Toast message
4. Also the User have to get all the newsletters from the Nullcast community thereafter.
5. Similar pages where the feature to be implemented are: -- What's New?, School of Ducks, Blog, Code of conduct etc.

**Expected behavior**
"Subscribe Our Newsletter" feature have to be functional in the listed pages of the Nullcast application

**Comment by jasirtp** [comment]
fixed working fine
