### ISSUE TITLE
Signing up of already registered user, displayed incorrect Toast messages from backend, when tried to Signed up again

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#357]
Signing up of already registered user, displayed incorrect Toast messages from backend, when tried to Signed up again.

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/
2. Enter the credentials of an already registered user in the Sign up Form
3. User is displayed an incorrect Toast messages from backend

**Expected behavior**
Already registered User when signing up, has to view proper Toast message -- according to already used username or Email

**Screenshot attached**
![Screenshot at 2021-11-02 09-49-40](https://user-images.githubusercontent.com/92918179/139787083-98419c3f-c05c-4278-a917-bd486b42160b.png)

**Desktop (please complete the following information):** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
**Smartphone:** not tested

**Additional context**
Tested in test site

**Comment by kunwar-11** [comment]
i will try to give it a shot

**Comment by thealpha93** [comment]
@kunwar-11 have at it

**Comment by kunwar-11** [comment]
i think for this we need to send a proper response from backend i can't differentiate whether the error is for email or username
