### ISSUE TITLE
Content changes and Inline code block of JS Course -- Chapter 13

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#364]
Content changes and Inline code block of JS Course -- Chapter 13

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/curriculum
2. Click on the Hyperlink "School of Ducks" in the header.
3. Scroll down to the Curriculum.
4. Click on "Learn More" button of Javascript, where User gets redirected to the Javascript Course page.
5. Click on the "Start" button, where the users gets redirected to the Javascript chapters page.
6. Click on the Bottom Hamburger icon where the Nav bar containing the menu of all the chapters listed.
7. User while learning through the chapters 13, could see some issues in contents and some technical terms which need to be given the Inline code block (single back tick), which are marked inside boxes.

**Expected behavior**
Content Changes and the Inline code block to be corrected in the JS chapters 13

**Screenshots attached**

**Desktop (please complete the following information):** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite

![13Asynchronous-Behaviour6](https://user-images.githubusercontent.com/92918179/140009740-16c8eb68-db53-4cee-b8e2-935dc2fda54e.png)
![13Asynchronous-Behaviour5](https://user-images.githubusercontent.com/92918179/140009741-6614bfb7-0a0e-40f3-948b-2393dad4cb6e.png)
![13Asynchronous-Behaviour4](https://user-images.githubusercontent.com/92918179/140009742-2f72e1e9-a439-4bf2-ad24-2d33675830f8.png)
![13Asynchronous-Behaviour3](https://user-images.githubusercontent.com/92918179/140009743-d809fc3c-3a1d-4a43-b976-c78b5bfa21c0.png)
![13Asynchronous-Behaviour2](https://user-images.githubusercontent.com/92918179/140009745-0744a665-293d-4a6a-b73f-ac3f8ab75fe9.png)
![13Asynchronous-Behaviour](https://user-images.githubusercontent.com/92918179/140009746-ba3d20ac-2425-4da0-85e3-e1101010633c.png)

**Comment by ajinkyajagdale21** [comment]
please assign it to me

**Comment by thealpha93** [comment]
@ajinkyajagdale21 GO ahead !

**Comment by thealpha93** [comment]
@ajinkyajagdale21 Note that the latest code is in `development` branch. So please submit your PR to 'development' branch

**Comment by ajinkyajagdale21** [comment]
sure
