### ISSUE TITLE
Content changes and Inline code block of JS Course -- Chapter 14

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#365]
Content changes and Inline code block of JS Course -- Chapter 14

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/curriculum
2. Click on the Hyperlink "School of Ducks" in the header.
3. Scroll down to the Curriculum.
4. Click on "Learn More" button of Javascript, where User gets redirected to the Javascript Course page.
5. Click on the "Start" button, where the users gets redirected to the Javascript chapters page.
6. Click on the Bottom Hamburger icon where the Nav bar containing the menu of all the chapters listed.
7. User while learning through the chapters 14, could see some issues in contents and some technical terms which need to be given the Inline code block (single back tick), which are marked inside boxes.

**Expected behavior**
Content Changes and the Inline code block to be corrected in the JS chapters 14

**Screenshots attached**

**Desktop (please complete the following information):** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite
![14Foreach-vs-Map-vs-Filter4](https://user-images.githubusercontent.com/92918179/140010004-c1e18d25-3479-43a3-8122-423306aead25.png)
![14Foreach-vs-Map-vs-Filter3](https://user-images.githubusercontent.com/92918179/140010007-9a152db5-d10d-427b-a35c-3f1015a8c362.png)
![14Foreach-vs-Map-vs-Filter2](https://user-images.githubusercontent.com/92918179/140010009-86f8ee12-2f21-436c-a975-13cbe093c28d.png)
![14Foreach-vs-Map-vs-Filter](https://user-images.githubusercontent.com/92918179/140010013-353eab50-c65c-400d-9dfe-10e0579e50b6.png)

**Comment by kunwar-11** [comment]
please assign it to me

**Comment by thealpha93** [comment]
Sure
