### ISSUE TITLE
Functioning of Multiple filters together in the Posts page -- Enhancement

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#434]
Functioning of Multiple filters together in the Posts page -- Tag filter and Status filter results can be clubbed together to provide the results needed for the User.

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. Click on the header "Write"
3. Click on both the Filters and user an choose the appropriate menu
4. Make functional of clubbing both the Filter results for the convenience of the user

**Expected behavior**
Clubbing both the Filter results in the Posts page for the convenience of the user can be made functional

**Screenshot attached**

**Desktop:** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone: Not tested
**Additional context**
Tested in test site
![Screenshot at 2021-11-11 10-06-54](https://user-images.githubusercontent.com/92918179/141237936-9638164e-4daf-440f-b668-d5796665bd7d.png)

**Comment by kunwar-11** [comment]
fixed
