### ISSUE TITLE
Browser when opened with the same user which was logged in yesterday displayed "Auth Failed" before doing any actions in the application

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#453]
Browser when opened with the same user which was logged in yesterday displayed "Auth Failed" before doing any actions in the application

**Steps To Reproduce**
1. Open the usual browser which the user uses
2. Open the nullcast test site
3. User could see the account still active in the browser
4. But "Auth Failed" toast message appears before doing any actions in the application

**Expected behavior**
User not be displayed "Auth Failed" message when the application is just opened or before doing any actions in the application

**Desktop:** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone (please complete the following information): Not tested
**Additional context**
Tested in test site

**Comment by kunwar-11** [comment]
not facing this now please check it once
