### ISSUE TITLE
Highlighting of the Youtube video url in the Blog Preview can be done for a better UX. -- Live site

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#462]
Highlighting of the Youtube video url in the Blog Preview can de done for a better UX.  Currently only Hand icon present while hovering

**Steps To Reproduce**
1. Go to https://nullcast.dev
2. Click on the header "Write" of the application of a logged in user
3. Click on "Add a Post" button
4. User after adding Youtube video URLs in the Blog and saved to draft
5. When previewed could see only hand icon over the URL while hovering
6. Can give a Highlighting effect or tooltip for a better UX experience

**Expected behavior**
Highlighting of the Youtube video url in the Blog Preview can be done for a better UX. 

**Screenshots attached**
Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone: Not tested
**Additional context**
Tested in Live site
![Screenshot at 2021-11-12 15-07-54](https://user-images.githubusercontent.com/92918179/141446493-2096bbe1-2e75-44e0-a85d-f5638831179a.png)
![Screenshot at 2021-11-12 15-07-40](https://user-images.githubusercontent.com/92918179/141446503-02fc12e3-dc03-4846-8fe6-afa0a2cf48cc.png)

**Comment by kiennguyenchi** [comment]
Hi there, I'm interested in this issue? Could you please assign it to me and specific file that I need to take a look at? Thank you!

**Comment by thealpha93** [comment]
@kiennguyenchi Sure. The file you need to look into is `pages/p/[postId].js

**Comment by thealpha93** [comment]
Here's the .env for our test site.
```
BASE_URL=https://test-api.nullcast.dev
CLIENT_URL=https://test-app.nullcast.dev
EDITOR_URL=https://test-editor.nullcast.dev
BUCKET_URL=https://n8o9asugsb.execute-api.us-east-1.amazonaws.com
SERVER_URL=http://test-api.nullcast.dev
```
@kiennguyenchi
