### ISSUE TITLE
Images of some of the Blogs listed in the Home page and also in the Blogs page, lacking clarity

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#482]
Images of some of the Blogs listed in the Home page and also in the Blogs page, lacking clarity

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User could see the Home page
3. User when scrolls down could view the Published Blogs of the users
4. User could notice, Images of some of the Blogs listed in the Home page and also in the Blogs page, lacking clarity
5. User clicks on "View All our Latest Posts", could also notice that the images of some of the Blogs being blurred in the Tile mode view

**Expected behavior**
Images of the Blogs listed in the Home page and also in the Blogs page, should be seen clearly by the users

**Screenshot attached**
Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in test app
![Screenshot at 2021-11-18 11-28-32](https://user-images.githubusercontent.com/92918179/142375029-90140342-1a12-40b7-89a1-1284e0f7537d.png)

**Comment by jasirtp** [comment]
tested and fixed
