### ISSUE TITLE
Supabase videos redirecting to the Homepage -- Need to add the Intro videos

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#491]
Supabase videos redirecting to the Homepage -- Need to add the Intro videos

**To Reproduce**
1. Go to https://test-app.nullcast.dev
2. Scroll down to the middle of the Home page after the Blog posts section.
3. User when clicks on the video buttons of the Supabase videos, its redirecting back to the Home page
4. Need to add the Intro videos

**Expected behavior**
User when clicks on the Supabase videos, have to display the Intro videos

Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in test site

**Comment by jasirtp** [comment]
branch updated pr request  pending
