### ISSUE TITLE
Full name validation to be fixed like the other fields in the Sign Up page

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#492]
All the other fields like Username, email and Password shows validation when Invalid data entered. But "Full name" field validation is displayed only when all the other fields are filled and so need to be fixed like the other fields in the Sign Up page

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. Click on Login Button, where user gets redirected to Login page
3. Click on the Sign Up button
4. Enter the User credentials in the Sign Up page
5. User could see that, "Full name" field validation is displayed only when all the other fields are filled and so need to be fixed like the other fields in the Sign Up page

**Expected behavior**
"Full name" field validation should be displayed like the other field validations of the Sign Up page

Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in test site

**Comment by kunwar-11** [comment]
Please assign it to me
