### ISSUE TITLE
"Logged in successfully" toast message missing when a user logs in successfully

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#493]
"Logged in successfully" toast message missing when a user logs in successfully to the application

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. Click on the Login button, where the User gets redirected to the login page
2. After entering User credentials, Click on Login Button, where user redirected to the Login page.
3. User could notice that, "Logged in successfully" missing when a user logs in successfully

**Expected behaviour**
"Logged in successfully" has to be displayed when a user logs in successfully

Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

Additional context
Tested in Testsite.

**Comment by rahmanharoon** [comment]
@thealpha93 can i work on this task

**Comment by thealpha93** [comment]
@rahmanharoon Sure

**Comment by thealpha93** [comment]
Make sure you branch out from the `development` branch

**Comment by asamad35** [comment]
Hello I would like to contribute but it seems already done.
