### ISSUE TITLE
No Enter Mark option available in the Heading row of the Blog Editing page

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#503]
No enter Mark option available in the Heading row of the Blog Editing page

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. Click on the "Write" page
3. Edit any of the Exisiting blogs of the User or else, create a new Blog
4. User while adding the Titles to the blog could notice that, No enter Mark option available in the Heading row of the Blog Editing page

**Expected behavior**
User while adding the Titles to the blog should have the option to use Enter Mark in the Heading row of the Blog Editing page

Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in test app
![Screenshot at 2021-11-19 13-42-04](https://user-images.githubusercontent.com/92918179/142588290-322a09df-0b88-46d8-896b-e0e002eff94a.png)

**Comment by thealpha93** [comment]
Closing this issue because this is not a relevant feat
