### ISSUE TITLE
Forgot your password page displayed when a user was created

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#508]
Forgot your password page displayed when a user was created

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets landed in the Home page of nullcast
3. Click on the Login Button, where users gets redirected to the Login page
4. Then click on the "Forgot Password" hyperlink
5. Then back to the Login page 
6. Click on the Sign Up button and Create an user
7. When the users signs up successfully, we could see that the "Forgot your password" page displayed again

**Expected Behavior**
When user signs up successfully, the "Forgot your Password" page should not be displayed and the user has to be redirected onto the Home page of the nullcast

Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in test app

https://user-images.githubusercontent.com/92918179/142606656-6a9731f8-053e-49a7-bdda-91a4e7c6784c.mp4

**Comment by Preetha007** [comment]
Issue not fixed in testapp.

**Comment by Preetha007** [comment]
Current issue resolved for Sign up; But when went through the same steps and when user got logged in, the same issue occurred for the login page of the user while logging in.

**Comment by kunwar-11** [comment]
fixed please check
