### ISSUE TITLE
Default photo or the uploaded photo not getting displayed in the Settings page in the "Change Photo" field

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#549]
Default photo or the uploaded photo not getting displayed in the Settings page in the "Change Photo" field

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/
2. Click on the Avatar menu, where the option "Settings" displayed
3. Inside the settings page, user could notice that the Default photo or the uploaded photo not getting displayed in the "Change Photo" field

**Expected behavior**
Default photo or the uploaded photo has to be displayed in the Settings page in the "Change Photo" field

**Recording attached**

Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone: Not tested
**Additional context**
Tested in test site

https://user-images.githubusercontent.com/92918179/143546640-9ee172bf-7d64-4aa1-a968-2efc14e27d9a.mp4

**Comment by jasirtp** [comment]
fixed
