### ISSUE TITLE
Change the "Donate" button to "Create" button in the Create-Events page

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#569]
Change the "Donate" button to "Create" button in the Create-Events page

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/
2. Enter the admin account "/admin/create-event" page
3. Change the "Donate" button to "Create" button in the Create-Events page
**Expected behaviour**
Change the "Donate" button to "Create" button in the Create-Events page

**Screenshot attached**
Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone: Not tested
**Additional context**
Tested in test site
![Screenshot at 2021-11-29 16-18-13](https://user-images.githubusercontent.com/92918179/143855071-08663f33-fb39-4dd6-ba82-6d68c3f00f40.png)

**Comment by kunwar-11** [comment]
already fixed
