### ISSUE TITLE
User when clicked on the "Write" page, displaying an error from the Backend.

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#577]
User when clicked on the "Write" page, displaying an error from the Backend

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User redirected to the Home page of Nullcast.
3. Click on the header "Write", where user gets navigated to the page of "Write" where blogs of the user gets listed
4. There the user could notice that when clicked on the "Write" page, displaying an error from the Backend in the "Write" page

**Expected behavior**
User when clicks on the "Write" page, should not display any error toast messages and just list the blogs created by the user

**Screenshot attached**

Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone: Not tested
**Additional context**
Tested in test site
![Screenshot at 2021-11-30 10-03-39](https://user-images.githubusercontent.com/92918179/143989393-41d04fc7-074a-4997-bfc2-1801dafc3472.png)

**Comment by jasirtp** [comment]
fixed
