### ISSUE TITLE
Publish-requested blogs needs to be saved, to display the contents in the Blog Edit page, if the user directly publishes without Saving to Draft

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#579]
Publish-requested blogs needs to be saved, to display the contents in the Blog Edit page, if the user directly publishes without Saving to Draft

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets redirected to the Home page
3. Click on the header "Write"
4. Click on "Add a Post" button
5. User could add blogs in the redirected blog edit page
6. But the contents of the blogs are visible in the Write page, only when Saved to Draft
7. If at all the user directly publishes without savingg, those contents of the blog won't get displayed
8. So Publish-requested blogs needs to be saved, to display the contents in the Blog Edit page, if the user directly publishes without Saving to Draft

**Expected behavior**
Publish-requested blogs needs to be saved, to display the contents in the Blog Edit page, if the user directly publishes without Saving to Draft

Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite

**Comment by jasirtp** [comment]
fixed
