### ISSUE TITLE
"View All" hyperlink can be added as in the designs, in the Followers column at the right end of the Profile page

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#581]
"View All" hyperlink can be added as in the designs, in the Followers column at the right end of the Profile page

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets redirected to the Homepage of Nullcast.
3. Click on the Login button
4. Enter the credentials and click on the Avatar icon where user gets navigated to the Profile page
5. In this page, in the "Followers" column at the right side, "View All" hyperlink can be added as per the designs
**Expected behavior**
"View All" hyperlink can be added as in the designs, which when clicked could display the expanded list of followers

**Figma link attached**
https://www.figma.com/proto/a7n18og4IhlfQr9bvj5pzC/Nullcast-design-share?node-id=64%3A1088&scaling=min-zoom&page-id=0%3A1

Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite

**Comment by kunwar-11** [comment]
fixed
