### ISSUE TITLE
Deletion of the Tags from the Profile-Settings page, with the Close button only clears the tags in the front-end, but deletes the tags only when individual click on the Close button of each tag-chip, clicked

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#583]
Deletion of the Tags from the Profile-Settings page, with the Close button only clears the tags in the front-end, but deletes the tags only when individual click on the Close button of each tag-chip, clicked

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets redirected to the Homepage of Nullcast.
3. Click on the Login button
4. Enter the credentials and click on the Avatar icon where user gets navigated to the Profile page
5. Click on the "Settings" option from the menu of the Avatar popover
6. User navigates to the Settings-Profile page
7. In the Settings-Profile page, Deletion of the Tags from the Profile-Settings page, with the Close button only clears the tags in the front-end, but deletes the tags only when individual click on the Close button of each tag-chip, clicked

**Expected behaviour**
Deletion of the Tags from the Profile-Settings page, with the Close button in the Skills dropdown field has to clear all the tags in both the front-end and backend. 

**Recording attached**
Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite

https://user-images.githubusercontent.com/92918179/144020316-60c25e77-4bfe-49cf-854c-384b2cf909a9.mp4

**Comment by jasirtp** [comment]
fixed
