### ISSUE TITLE
Application error occured when the user clicked on the "+ xx more" skills in the Profile page

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#594]
Application error occured when the user clicked on the "+ xx more" skills in the Profile page

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets redirected to the Homepage of Nullcast.
3. Click on the Login button
4. Enter the credentials and click on the Avatar icon where user gets navigated to the Profile page
5. User updated with several skills if clicked on "+xx more" skills in the Profile page, could notice that an application error occured in the Profile page
**Expected behaviour**
When user clicks on the "+ xx more" skills in the Profile page, should list out the skills added by the user in the Settings-profile page
**Recording attached**
Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite

https://user-images.githubusercontent.com/92918179/144052585-c2101c57-af1b-4311-ae92-d2b91ff686c0.mp4

**Comment by jasirtp** [comment]
fixed
