### ISSUE TITLE
"Update Password" feature not updating the Passwords and displaying an error toast message from the Backend

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#597]
"Update Password" feature not updating the Passwords and displaying an error toast message from the Backend

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets redirected to the Homepage of Nullcast.
3. Click on the Login button
4. Enter the credentials and click on the Avatar icon where user gets navigated to the Profile page
5. Click on the "Settings" option from the menu of the Avatar popover
6. User navigates to the Settings-Profile page
7. In the Settings-Profile page, "Update Password" feature not updating the Passwords and displaying an error toast message from the Backend

**Expected behaviour**
"Update Password" feature should update the Passwords and displaying success toast message 

**Screenshot attached**
Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite
![Screenshot at 2021-11-30 19-04-08](https://user-images.githubusercontent.com/92918179/144058605-b6ed163e-6e28-4b09-8d4c-0c7f1c784749.png)

**Comment by jasirtp** [comment]
fixed
