### ISSUE TITLE
When user clicks on "Add a Post" from the 'Write" page itself, a toast message is displayed which is to be fixed

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#610]
When user clicks on "Add a Post" from the 'Write" page itself, a toast message is displayed which is to be fixed

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets redirected to the Homepage of Nullcast.
3. Click on the "Write" page
4. Then click on the "Add a Post" button
5. User could notice that, When user clicks on "Add a Post" from the 'Write" page itself, a toast message is displayed which is to be fixed

**Expected behaviour**
When user clicks on "Add a Post" from the 'Write" page, a toast message has to be displayed only when the user adds the blog on the Add a Post page

**Screenshot attached**
Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite

https://user-images.githubusercontent.com/92918179/144184294-0198a4c7-2568-4567-af31-b1f55385770b.mp4

**Comment by jasirtp** [comment]
fixed
