### ISSUE TITLE
The latest status of the Blogs are not listed in the Admin profile

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#633]
The latest status of the Blogs are not listed in the Admin profile

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. Click on the"Write" page
3. User could add or edit the blogs
4. And that status has to be listed in the User's profile as well as in the Admin profile
5. But, The latest status of the Blogs are not listed in the Admin profile

**Expected behavior**
The latest status of the Blogs should be listed in the Admin profile
**Screenshot Attached**

Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in test app
![Screenshot at 2021-12-02 17-55-28](https://user-images.githubusercontent.com/92918179/144422957-e1e9dca4-6bd7-4557-8a50-2b8845a82bb0.png)
![Screenshot at 2021-12-02 17-55-44](https://user-images.githubusercontent.com/92918179/144422965-0a25cd5c-7348-436b-9631-8a662691e627.png)

**Comment by kunwar-11** [comment]
its's working please check before closing
