### ISSUE TITLE
Events should not be created with the Previous date and time. Especially previous time of the current or previous days

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#659]
Events should not be created with the Previous date and time. Especially previous time of the current or previous days

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/
2. Enter the Admin account "/admin/events"
3. Add an Event by entering all the data in the fields of the Create Event page
4. After the Event got created, User noticed that he was able to create Events in the Current day but with a previous time
**Expected behaviour**
Events should not be created with the Previous date and time. Especially previous time of the current or previous days

**Screenshot attached**

Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone: Not tested
**Additional context**
Tested in test site
![Screenshot at 2021-12-06 16-05-58](https://user-images.githubusercontent.com/92918179/144831459-5ffcd9f4-68db-40cd-b1fa-0db2f1edaf27.png)

**Comment by kunwar-11** [comment]
fixed
