### ISSUE TITLE
Image of the Organizer not getting displayed in the Events details page

### ISSUE THREAD

**Issue by Preetha007** [Planet-NULLCAST/curriculum#662]
Image of the Organizer not getting displayed in the Events details page

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/
2. Enter the Admin account "/admin/events"
3. Add an Event by entering all the data in the fields of the Create Event page
4. After the Event got created, it gets listed in the Events page in the normal users profile
5. Normal users could notice that Image of the Organizer not getting displayed in the Events details page
**Expected behaviour**
Image of the Organizer not getting displayed in the Events details page
**Screenshot attached**
Desktop: ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
Smartphone: Not tested
**Additional context**
Tested in test site
![Screenshot at 2021-12-06 16-35-09](https://user-images.githubusercontent.com/92918179/144837085-c91c22c6-effb-4dc4-a9a3-c89d900b77eb.png)
![Screenshot at 2021-12-06 16-48-10](https://user-images.githubusercontent.com/92918179/144837149-f8e2c9f6-aef5-4f5d-a97d-8047022dca67.png)

**Comment by jasirtp** [comment]
fixed
