### ISSUE TITLE
Unauthorized users gets redirected to 404 page on viewing blog preview

### ISSUE THREAD

**Issue by thealpha93** [Planet-NULLCAST/curriculum#881]
**Describe the bug**
Unauthorized users gets redirected to 404 page on viewing blog preview

**To Reproduce**
1.Log out from the platform
2. Try to visit the preview page of a blog
3. You get redirected to 404

**Expected behavior**
The preview of the page should be shown

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Brave

**Comment by johnbabu021** [comment]
do close
